######################################
#
# BUSCO summary figure
# @version 4.0.0
# @since BUSCO 2.0.0
# 
# Copyright (c) 2015-2024, Evgeny Zdobnov (ez@ezlab.org)
# Licensed under the MIT license. See LICENSE.md file.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("BUSCO_summaries/","busco_figure.png",sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "BUSCO Assessment Results"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('07-DH-33_wild_cabbage', '07-DH-33_wild_cabbage', '07-DH-33_wild_cabbage', '07-DH-33_wild_cabbage', '6-9-28_wild_cabbage', '6-9-28_wild_cabbage', '6-9-28_wild_cabbage', '6-9-28_wild_cabbage', 'HDEM', 'HDEM', 'HDEM', 'HDEM', 'T19_chinese_kale', 'T19_chinese_kale', 'T19_chinese_kale', 'T19_chinese_kale', 'T17_collard_greens', 'T17_collard_greens', 'T17_collard_greens', 'T17_collard_greens', 'T10_wild_cabbage', 'T10_wild_cabbage', 'T10_wild_cabbage', 'T10_wild_cabbage', 'cauliflower', 'cauliflower', 'cauliflower', 'cauliflower', 'T07_kohlrabi', 'T07_kohlrabi', 'T07_kohlrabi', 'T07_kohlrabi', 'W1701_wild_cabbage', 'W1701_wild_cabbage', 'W1701_wild_cabbage', 'W1701_wild_cabbage', 'T02_flat_cabbage', 'T02_flat_cabbage', 'T02_flat_cabbage', 'T02_flat_cabbage', 'T04_pointed_cabbage', 'T04_pointed_cabbage', 'T04_pointed_cabbage', 'T04_pointed_cabbage', 'T09_wild_cabbage', 'T09_wild_cabbage', 'T09_wild_cabbage', 'T09_wild_cabbage', 'T08_brussels_sprouts', 'T08_brussels_sprouts', 'T08_brussels_sprouts', 'T08_brussels_sprouts', 'T16_perpetual_kale', 'T16_perpetual_kale', 'T16_perpetual_kale', 'T16_perpetual_kale', 'BOL', 'BOL', 'BOL', 'BOL', 'M249_wild_cabbage', 'M249_wild_cabbage', 'M249_wild_cabbage', 'M249_wild_cabbage', 'T24_broccoli', 'T24_broccoli', 'T24_broccoli', 'T24_broccoli', 'T11_chinese_kale', 'T11_chinese_kale', 'T11_chinese_kale', 'T11_chinese_kale', 'D101_wild_cabbage', 'D101_wild_cabbage', 'D101_wild_cabbage', 'D101_wild_cabbage', 'broccoli', 'broccoli', 'broccoli', 'broccoli', 'T15_tronchuda_kale', 'T15_tronchuda_kale', 'T15_tronchuda_kale', 'T15_tronchuda_kale', 'PL021_wild_cabbage', 'PL021_wild_cabbage', 'PL021_wild_cabbage', 'PL021_wild_cabbage', 'JZS_v2', 'JZS_v2', 'JZS_v2', 'JZS_v2', 'T25_cauliflower', 'T25_cauliflower', 'T25_cauliflower', 'T25_cauliflower', 'OX_heart', 'OX_heart', 'OX_heart', 'OX_heart')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(length(levels(my_species)):1)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(88.4, 8.9, 0.7, 2.0, 89.0, 9.3, 0.7, 1.0, 86.9, 9.3, 0.6, 3.2, 87.8, 9.5, 0.5, 2.2, 81.7, 12.3, 0.9, 5.1, 88.2, 9.7, 0.2, 1.9, 87.0, 9.5, 0.3, 3.2, 87.2, 9.7, 0.5, 2.6, 88.6, 9.5, 0.8, 1.1, 88.4, 9.6, 0.4, 1.6, 87.4, 9.7, 0.8, 2.1, 87.4, 9.9, 0.7, 2.0, 87.9, 9.6, 0.5, 2.0, 84.3, 12.1, 0.5, 3.1, 89.9, 9.4, 0.2, 0.5, 89.3, 8.9, 0.6, 1.2, 87.8, 9.7, 0.5, 2.0, 86.5, 9.6, 0.9, 3.0, 89.1, 9.1, 0.5, 1.3, 88.5, 9.9, 0.3, 1.3, 86.4, 10.0, 0.8, 2.8, 88.5, 9.8, 0.6, 1.1, 86.7, 10.7, 0.4, 2.2, 87.4, 9.6, 0.6, 2.4, 85.6, 9.1, 0.9, 4.4)
my_values <- c(4061, 408, 32, 95, 4090, 429, 30, 47, 3993, 429, 28, 146, 4035, 438, 21, 102, 3754, 566, 41, 235, 4055, 445, 11, 85, 4000, 436, 13, 147, 4007, 445, 21, 123, 4073, 437, 38, 48, 4064, 442, 19, 71, 4017, 445, 35, 99, 4015, 455, 33, 93, 4039, 439, 25, 93, 3873, 558, 21, 144, 4134, 433, 9, 20, 4104, 411, 27, 54, 4036, 445, 21, 94, 3975, 439, 42, 140, 4093, 417, 22, 64, 4067, 454, 12, 63, 3969, 460, 35, 132, 4067, 452, 27, 50, 3984, 492, 18, 102, 4015, 439, 26, 116, 3935, 416, 41, 204)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), position = position_stack(reverse = TRUE), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, hjust=0.5, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
print("Done")
