### PATHS ###

# directory of genomic fasta sequences with .fna extension
genomes: brassica/genomes

# directory of annotations with .gff3 extension
annotations: brassica/annotations

# table of matching genome and annotation files
data_table:

# custom scratch directory (default is system default)
scratch:

# output data directories
filtered_genomes: brassica/genomes_filtered
filtered_annotations: brassica/annotations_filtered
proteins: brassica/proteins
functions: brassica/functions
statistics: brassica/statistics
metadata: brassica/metadata

### PARAMETERS ###

# minimum sequence length for the genomic fasta
min_len: 1000

# only keep features of longest isoform
longest_isoform: True

# minimum size of the CDS open reading frame
orf_size: 30

# comma separated list of InterProScan analyses
applications: "TIGRFAM,Pfam"
