######################################
#
# BUSCO summary figure
# @version 4.0.0
# @since BUSCO 2.0.0
# 
# Copyright (c) 2015-2024, Evgeny Zdobnov (ez@ezlab.org)
# Licensed under the MIT license. See LICENSE.md file.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("BUSCO_summary_files/","busco_figure.png",sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "BUSCO Assessment Results"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('savoy_cabbage_T03', 'savoy_cabbage_T03', 'savoy_cabbage_T03', 'savoy_cabbage_T03', 'tree_kale_T13', 'tree_kale_T13', 'tree_kale_T13', 'tree_kale_T13', 'cauliflower_T21', 'cauliflower_T21', 'cauliflower_T21', 'cauliflower_T21', 'juncea_PM', 'juncea_PM', 'juncea_PM', 'juncea_PM', 'kohlrabi_T27', 'kohlrabi_T27', 'kohlrabi_T27', 'kohlrabi_T27', 'juncea_Xcgenome', 'juncea_Xcgenome', 'juncea_Xcgenome', 'juncea_Xcgenome', 'ornamental_kale_T18', 'ornamental_kale_T18', 'ornamental_kale_T18', 'ornamental_kale_T18', 'scotch_kale_T14', 'scotch_kale_T14', 'scotch_kale_T14', 'scotch_kale_T14', 'round_cabbage_T06', 'round_cabbage_T06', 'round_cabbage_T06', 'round_cabbage_T06', 'lacimato_kale_T12', 'lacimato_kale_T12', 'lacimato_kale_T12', 'lacimato_kale_T12', 'scotch_kale_T26', 'scotch_kale_T26', 'scotch_kale_T26', 'scotch_kale_T26', 'juncea_HJ', 'juncea_HJ', 'juncea_HJ', 'juncea_HJ')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(length(levels(my_species)):1)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(86.4, 9.4, 0.7, 3.5, 87.3, 9.9, 0.5, 2.3, 87.5, 9.8, 0.6, 2.1, 10.8, 85.9, 0.5, 2.8, 87.0, 9.5, 0.8, 2.7, 7.2, 91.7, 0.1, 1.0, 88.1, 9.3, 0.3, 2.3, 87.1, 9.5, 0.7, 2.7, 87.6, 9.8, 0.5, 2.1, 88.0, 9.7, 0.3, 2.0, 86.7, 10.0, 0.4, 2.9, 22.8, 76.4, 0.4, 0.4)
my_values <- c(3970, 433, 32, 161, 4014, 456, 22, 104, 4020, 450, 26, 100, 498, 3947, 25, 126, 3999, 438, 36, 123, 331, 4214, 4, 47, 4050, 427, 16, 103, 4004, 438, 32, 122, 4024, 450, 25, 97, 4043, 447, 15, 91, 3985, 458, 20, 133, 1047, 3513, 17, 19)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), position = position_stack(reverse = TRUE), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, hjust=0.5, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
print("Done")
